### ISSUE TITLE
Jason and Daisy

### ISSUE THREAD

**Issue by Kichihei6** [chell-uoxou/PHP-Prompt-OS#4]
PHPPO, PHPPO,
Not PHP, PHPPO.
I want PC very much I want to PC.
Anyway let's go near PC-shop.
I encountered a terrorism seriously manji.
PHPPO.
I bought shampoo-hat.
I threw it in field with happily.
It fell down without flying so much.
PHPPO.
There was a doll of catfish.
I wanted to get it wear glasses.
But it's impossible due to it have no ears.
PHPPO.
There was a hat on a sofa
So I smelled it immediately.
Strangely it smelled of vanilla.
PHPPO
Power my PC up.
Connected to Internet.
My PC had been infected virus.
PHPPO.
What is PHPPO? What is PHPPO? What is PHPPO?
PHPPO.

**Comment by chell-uoxou** [comment]
Nope.

**Comment by Kichihei6** [comment]
:doge:
